---

- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: install requiered packages
      apt: name={{ item }} state=present
      with_items:
        - apache2
        - mysql-server
        - php5
